### ISSUE TITLE
How come this supports unicode characters?

### ISSUE THREAD

**Issue by zippoxer** [fvbock/trie#1]
I've peeked the code, and I can see this library deals with first byte of the given string, instead of first rune. The first byte of a UTF-8 string isn't necessarily it's first character, thus two different letters may have the same first byte. Read https://blog.golang.org/strings

Or am I getting this wrong?

**Comment by fvbock** [comment]
hi @zippoxer 

oh. been a while i have looked here...

the index is created based on bytes not runes. so if two strings share the first byte and differ afterwards you get two branches after the first byte...

the reason for doing it this way is that even though the tree gets deeper the width per branch is limited (max 256) which was relevant performance wise for my original application and might not be for other types of corpora being indexed.

anyways: the lib does support unicode - just indexes them based on their (possibly multiple) bytes per character - not their character runes.
